In [46]:
from selenium import webdriver
from bs4 import BeautifulSoup
import urllib
import pandas as pd
import requests

In [47]:
driver = webdriver.Chrome(executable_path='/Users/olga/Downloads/chromedriver')

In [48]:
driver.get("https://www.gigantti.fi/INTERSHOP/web/WFS/store-gigantti-Site/fi_FI/-/EUR/CC_RecommendedProductsViewAll-Start?PageletUUID=WAqsGQV9EscAAAFmy6WN8A_L")
content = driver.page_source

In [50]:
products=[] #List to store name of the product
prices=[] #List to store price of the product
energy_class=[] #List to store energy class of the product

In [51]:
#Getting products description
soup2 = BeautifulSoup(content, 'html.parser')
nameList = soup2.findAll('a', attrs={'class':'product-name'})
for name in nameList:
    products.append(name.text)
print(products)

df1= pd.DataFrame({'Product Name':products})

['\nElectrolux astianpesukone ESF5206LOX (ruostumaton teräs)\n', '\nMiele astianpesukone G5022SCUBRWS (valkoinen)\n', '\nBosch Series 2 astianpesukone SMU2ITW04S (valkoinen)\n', '\nAsko astianpesukone DBI8237W1 (valkoinen)\n', '\nBosch Series 6 astianpesukone SMU6ZDW76S (valkoinen)\n', '\nBosch Series 4 astianpesukone SMU4HAI48S (teräs/hopea)\n', '\nMiele astianpesukone G5000UBRWS\n', '\nBosch astianpesukone SMU4EDW73S (valkoinen)\n', '\nBosch Series 6 astianpesukone SMU6ECS75S (ruostumaton teräs)\n', '\nElectrolux astianpesukone CSF5500LOW (valkoinen)\n', '\nLogik Slimline astianpesukone LDWE45W20N\n', '\nLogik Slimline astianpesukone LDW45W20N\n', '\nMiele astianpesukone G5022SCUCLST (teräs)\n', '\nElectrolux astianpesukone ESF5533LOW (valkoinen)\n', '\nElectrolux astianpesukone ESF5206LOW (valkoinen)\n', '\nBosch Series 2 astianpesukone SMU24AW01S\n', '\nMiele astianpesukone G7155SCVIXXL\n', '\nBosch Series 2 astianpesukone SPU2IKW02S (valkoinen)\n']

In [52]:
df1

                                         Product Name
0   \nElectrolux astianpesukone ESF5206LOX (ruostu...
1   \nMiele astianpesukone G5022SCUBRWS (valkoinen)\n
2   \nBosch Series 2 astianpesukone SMU2ITW04S (va...
3       \nAsko astianpesukone DBI8237W1 (valkoinen)\n
4   \nBosch Series 6 astianpesukone SMU6ZDW76S (va...
5   \nBosch Series 4 astianpesukone SMU4HAI48S (te...
6                 \nMiele astianpesukone G5000UBRWS\n
7     \nBosch astianpesukone SMU4EDW73S (valkoinen)\n
8   \nBosch Series 6 astianpesukone SMU6ECS75S (ru...
9   \nElectrolux astianpesukone CSF5500LOW (valkoi...
10       \nLogik Slimline astianpesukone LDWE45W20N\n
11        \nLogik Slimline astianpesukone LDW45W20N\n
12      \nMiele astianpesukone G5022SCUCLST (teräs)\n
13  \nElectrolux astianpesukone ESF5533LOW (valkoi...
14  \nElectrolux astianpesukone ESF5206LOW (valkoi...
15       \nBosch Series 2 astianpesukone SMU24AW01S\n
16              \nMiele astianpesukone G7155SCVIXXL\n
17  \nBosch Series 2 astianpesukone SPU2IKW02S (va...

In [53]:
df1['Product Name'] = df1['Product Name'].str[1:]
df1

                                         Product Name
0   Electrolux astianpesukone ESF5206LOX (ruostuma...
1     Miele astianpesukone G5022SCUBRWS (valkoinen)\n
2   Bosch Series 2 astianpesukone SMU2ITW04S (valk...
3         Asko astianpesukone DBI8237W1 (valkoinen)\n
4   Bosch Series 6 astianpesukone SMU6ZDW76S (valk...
5   Bosch Series 4 astianpesukone SMU4HAI48S (terä...
6                   Miele astianpesukone G5000UBRWS\n
7       Bosch astianpesukone SMU4EDW73S (valkoinen)\n
8   Bosch Series 6 astianpesukone SMU6ECS75S (ruos...
9   Electrolux astianpesukone CSF5500LOW (valkoine...
10         Logik Slimline astianpesukone LDWE45W20N\n
11          Logik Slimline astianpesukone LDW45W20N\n
12        Miele astianpesukone G5022SCUCLST (teräs)\n
13  Electrolux astianpesukone ESF5533LOW (valkoine...
14  Electrolux astianpesukone ESF5206LOW (valkoine...
15         Bosch Series 2 astianpesukone SMU24AW01S\n
16                Miele astianpesukone G7155SCVIXXL\n
17  Bosch Series 2 astianpesukone SPU2IKW02S (valk...

In [54]:
#Getting products price
soup3 = BeautifulSoup(content, 'html.parser')
nameList2 = soup3.findAll('div', attrs={'class':'product-price'})
for price in nameList2:
    prices.append(price.text)
print(prices)

['349\n\xa0\n\xa0\n', '849\n\xa0\n\xa0\n', '349\n\xa0\n\xa0\n', '599\n\xa0\n\xa0\n', '999\n\xa0\n\xa0\n', '599\n\xa0\n\xa0\n', '549\n\xa0\n\xa0\n', '699\n\xa0\n\xa0\n', '1\xa0049\n\xa0\n\xa0\n', '499\n\xa0\n\xa0\n', '199\n\xa0\n\xa0\n', '399\n\xa0\n\xa0\n', '979\n\xa0\n\xa0\n', '329\n\xa0\n\xa0\n', '269\n\xa0\n\xa0\n', '339\n\xa0\n\xa0\n', '1\xa0349\n\xa0\n\xa0\n', '479\n\xa0\n\xa0\n']

In [55]:
df2= pd.DataFrame({'Price':prices}) 
df2

            Price
0     349\n \n \n
1     849\n \n \n
2     349\n \n \n
3     599\n \n \n
4     999\n \n \n
5     599\n \n \n
6     549\n \n \n
7     699\n \n \n
8   1 049\n \n \n
9     499\n \n \n
10    199\n \n \n
11    399\n \n \n
12    979\n \n \n
13    329\n \n \n
14    269\n \n \n
15    339\n \n \n
16  1 349\n \n \n
17    479\n \n \n

In [56]:
df2['Price'] = df2['Price'].str.replace('\n','')
df2

      Price
0     349
1     849
2     349
3     599
4     999
5     599
6     549
7     699
8   1 049
9     499
10    199
11    399
12    979
13    329
14    269
15    339
16  1 349
17    479

In [57]:
df= pd.concat([df1,df2], ignore_index=True, axis=1)
df

                                                    0        1
0   Electrolux astianpesukone ESF5206LOX (ruostuma...    349
1     Miele astianpesukone G5022SCUBRWS (valkoinen)\n    849
2   Bosch Series 2 astianpesukone SMU2ITW04S (valk...    349
3         Asko astianpesukone DBI8237W1 (valkoinen)\n    599
4   Bosch Series 6 astianpesukone SMU6ZDW76S (valk...    999
5   Bosch Series 4 astianpesukone SMU4HAI48S (terä...    599
6                   Miele astianpesukone G5000UBRWS\n    549
7       Bosch astianpesukone SMU4EDW73S (valkoinen)\n    699
8   Bosch Series 6 astianpesukone SMU6ECS75S (ruos...  1 049
9   Electrolux astianpesukone CSF5500LOW (valkoine...    499
10         Logik Slimline astianpesukone LDWE45W20N\n    199
11          Logik Slimline astianpesukone LDW45W20N\n    399
12        Miele astianpesukone G5022SCUCLST (teräs)\n    979
13  Electrolux astianpesukone ESF5533LOW (valkoine...    329
14  Electrolux astianpesukone ESF5206LOW (valkoine...    269
15         Bosch Series 2 astianpesukone SMU24AW01S\n    339
16                Miele astianpesukone G7155SCVIXXL\n  1 349
17  Bosch Series 2 astianpesukone SPU2IKW02S (valk...    479

In [58]:
df=df.rename(columns={0: "Product", 1: "Price"})
df

                                              Product    Price
0   Electrolux astianpesukone ESF5206LOX (ruostuma...    349
1     Miele astianpesukone G5022SCUBRWS (valkoinen)\n    849
2   Bosch Series 2 astianpesukone SMU2ITW04S (valk...    349
3         Asko astianpesukone DBI8237W1 (valkoinen)\n    599
4   Bosch Series 6 astianpesukone SMU6ZDW76S (valk...    999
5   Bosch Series 4 astianpesukone SMU4HAI48S (terä...    599
6                   Miele astianpesukone G5000UBRWS\n    549
7       Bosch astianpesukone SMU4EDW73S (valkoinen)\n    699
8   Bosch Series 6 astianpesukone SMU6ECS75S (ruos...  1 049
9   Electrolux astianpesukone CSF5500LOW (valkoine...    499
10         Logik Slimline astianpesukone LDWE45W20N\n    199
11          Logik Slimline astianpesukone LDW45W20N\n    399
12        Miele astianpesukone G5022SCUCLST (teräs)\n    979
13  Electrolux astianpesukone ESF5533LOW (valkoine...    329
14  Electrolux astianpesukone ESF5206LOW (valkoine...    269
15         Bosch Series 2 astianpesukone SMU24AW01S\n    339
16                Miele astianpesukone G7155SCVIXXL\n  1 349
17  Bosch Series 2 astianpesukone SPU2IKW02S (valk...    479

In [62]:
#Getting products energy class
soup4 = BeautifulSoup(content, 'html.parser')
nameList3 = soup4.findAll('text',attrs={'class':"basic-text-svg"})[0::2]
for ii in nameList3:
    energy_class.append(ii.text)
print(energy_class)

['\nA+', '\nA++', '\nA+', '\nA+++', '\nA+++', '\nA++', '\nA++', '\nA+++', '\nA+', '\nA++', '\nA++', '\nA+++', '\nA++', '\nA++', '\nA+', '\nA+', '\nA+++', '\nA+']

In [63]:
df3= pd.DataFrame({'Energy class':energy_class}) 
df3

   Energy class
0          \nA+
1         \nA++
2          \nA+
3        \nA+++
4        \nA+++
5         \nA++
6         \nA++
7        \nA+++
8          \nA+
9         \nA++
10        \nA++
11       \nA+++
12        \nA++
13        \nA++
14         \nA+
15         \nA+
16       \nA+++
17         \nA+

In [64]:
df3['Energy class'] = df3['Energy class'].str.replace('\n','')
df3

   Energy class
0            A+
1           A++
2            A+
3          A+++
4          A+++
5           A++
6           A++
7          A+++
8            A+
9           A++
10          A++
11         A+++
12          A++
13          A++
14           A+
15           A+
16         A+++
17           A+

In [65]:
df= pd.concat([df,df3], ignore_index=True, axis=1)
df

                                                    0        1     2
0   Electrolux astianpesukone ESF5206LOX (ruostuma...    349      A+
1     Miele astianpesukone G5022SCUBRWS (valkoinen)\n    849     A++
2   Bosch Series 2 astianpesukone SMU2ITW04S (valk...    349      A+
3         Asko astianpesukone DBI8237W1 (valkoinen)\n    599    A+++
4   Bosch Series 6 astianpesukone SMU6ZDW76S (valk...    999    A+++
5   Bosch Series 4 astianpesukone SMU4HAI48S (terä...    599     A++
6                   Miele astianpesukone G5000UBRWS\n    549     A++
7       Bosch astianpesukone SMU4EDW73S (valkoinen)\n    699    A+++
8   Bosch Series 6 astianpesukone SMU6ECS75S (ruos...  1 049      A+
9   Electrolux astianpesukone CSF5500LOW (valkoine...    499     A++
10         Logik Slimline astianpesukone LDWE45W20N\n    199     A++
11          Logik Slimline astianpesukone LDW45W20N\n    399    A+++
12        Miele astianpesukone G5022SCUCLST (teräs)\n    979     A++
13  Electrolux astianpesukone ESF5533LOW (valkoine...    329     A++
14  Electrolux astianpesukone ESF5206LOW (valkoine...    269      A+
15         Bosch Series 2 astianpesukone SMU24AW01S\n    339      A+
16                Miele astianpesukone G7155SCVIXXL\n  1 349    A+++
17  Bosch Series 2 astianpesukone SPU2IKW02S (valk...    479      A+

In [66]:
df=df.rename(columns={0: "Product", 1: "Price", 2: "Energy class"})
df

                                              Product    Price Energy class
0   Electrolux astianpesukone ESF5206LOX (ruostuma...    349             A+
1     Miele astianpesukone G5022SCUBRWS (valkoinen)\n    849            A++
2   Bosch Series 2 astianpesukone SMU2ITW04S (valk...    349             A+
3         Asko astianpesukone DBI8237W1 (valkoinen)\n    599           A+++
4   Bosch Series 6 astianpesukone SMU6ZDW76S (valk...    999           A+++
5   Bosch Series 4 astianpesukone SMU4HAI48S (terä...    599            A++
6                   Miele astianpesukone G5000UBRWS\n    549            A++
7       Bosch astianpesukone SMU4EDW73S (valkoinen)\n    699           A+++
8   Bosch Series 6 astianpesukone SMU6ECS75S (ruos...  1 049             A+
9   Electrolux astianpesukone CSF5500LOW (valkoine...    499            A++
10         Logik Slimline astianpesukone LDWE45W20N\n    199            A++
11          Logik Slimline astianpesukone LDW45W20N\n    399           A+++
12        Miele astianpesukone G5022SCUCLST (teräs)\n    979            A++
13  Electrolux astianpesukone ESF5533LOW (valkoine...    329            A++
14  Electrolux astianpesukone ESF5206LOW (valkoine...    269             A+
15         Bosch Series 2 astianpesukone SMU24AW01S\n    339             A+
16                Miele astianpesukone G7155SCVIXXL\n  1 349           A+++
17  Bosch Series 2 astianpesukone SPU2IKW02S (valk...    479             A+

In [67]:
df.to_csv (r'/Users/olga/Python_course\Gigantti.csv', index = False, header=True)